src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CalendarRepository::class)
 */
class Calendar
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $all_day;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $background_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $border_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $text_color;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $delais;

    /**
     * @ORM\Column(type="date")
     */
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $theme;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $localisation;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user",referencedColumnName="id")
     */
    private $User;





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;

    }



    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->title;
    }

    public function setTitre(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }





    public function getDelais(): ?string
    {
        return $this->delais;
    }

    public function setDelais(string $delais): self
    {
        $this->delais = $delais;

        return $this;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->User;
    }

    /**
     * @param User $User
     * @return Calendar
     */
    public function setUser(User $User): Calendar
    {
        $this->User = $User;
        return $this;
    }





}

src/Entity/Template.php
<?php

namespace App\Entity;

use App\Repository\TemplateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TemplateRepository::class)
 */
class Template
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $chemin;

    /**
     * @ORM\OneToMany(targetEntity=Page::class, mappedBy="template")
     */
    private $pages;

    public function __construct()
    {
        $this->pages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getChemin(): ?string
    {
        return $this->chemin;
    }

    public function setChemin(string $chemin): self
    {
        $this->chemin = $chemin;

        return $this;
    }

    /**
     * @return Collection|Page[]
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Page $page): self
    {
        if (!$this->pages->contains($page)) {
            $this->pages[] = $page;
            $page->setTemplate($this);
        }

        return $this;
    }

    public function removePage(Page $page): self
    {
        if ($this->pages->removeElement($page)) {
            // set the owning side to null (unless already changed)
            if ($page->getTemplate() === $this) {
                $page->setTemplate(null);
            }
        }

        return $this;
    }
}

src/Form/OffresType.php
<?php

namespace App\Form;

use App\Entity\Offres;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OffresType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type')
            ->add('titre')
            ->add('nombre')
            ->add('description', TextareaType::class ,[
                "attr" =>[
                    "class"=>"form-control"
                ]
            ] )
            /*->add('date')*/
            ->add('date'
                , DateTimeType
                ::class, ['widget' => 'single_text','html5' => false,'attr' => ['class' => 'datepicker'],])
            ->add('qualification')
            ->add('experience')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Offres::class,
        ]);
    }
}

src/Controller/OffresController.php
<?php

namespace App\Controller;


use App\Entity\Article;
use App\Entity\Condidature;
use App\Entity\Formation;
use App\Entity\Offres;
use App\Entity\Valpub;
use App\Form\OffresType;

use App\Repository\ArticleRepository;
use App\Repository\OffresRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/offres")
 */
class OffresController extends AbstractController
{
    /**
     * @Route("/", name="offres_index", methods={"GET"})
     */
    public function index(OffresRepository $offresRepository,ArticleRepository $articlerepo,Request $request,PaginatorInterface $paginator)
    {


        $em=$this->getDoctrine()->getManager();
        $articlelast1 = $articlerepo->findLastArticles2();

        $search = $request->query->get('o');
        if ($search) {
            $offres = $offresRepository->searchBack($search);
        } else {
            $offres = $offresRepository->createQueryBuilder('offre')->select('offre')->getQuery();
        }

        $offre = $paginator->paginate(
            $offres,
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('offres/index.html.twig', [
            'offres' => $offre,'articlelast1' => $articlelast1
        ]);
    }
    public function search(OffresRepository  $offresRepository, Request $request)
    { $search = $request->query->get('o');
        if ($search) {
            $offres = $offresRepository->searchBack($search);
        } else {
            $offres = $offresRepository->findAllOrdered();
        }
    }
    /**
     * @Route("/liste", name="offresF_index", methods={"GET"})
     */
    public function liste(OffresRepository $offresRepository,Request $request,PaginatorInterface $paginator,ArticleRepository $articlerepo)
    {

        $articlelast1 = $articlerepo->findLastArticles2();

        $search = $request->query->get('o');
        $tes=0;
        if ($request->query->get('tes')){
            $tes= $request->query->get('tes');
        }

        if ($search!="" or $tes!=0) {
            $offres = $offresRepository->search($search,$tes);
        } else {
            $offres = $offresRepository->createQueryBuilder('offre')->select('offre')->getQuery();
        }

        $offre = $paginator->paginate(
            $offres,
            $request->query->getInt('page', 1),
            4
        );

        return $this->render('offres/index2.html.twig', [
            'offres' => $offre,'articlelast1' => $articlelast1
        ]);
    }

    /**
     * @Route("/new", name="offres_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        $offre = new Offres();
        $form = $this->createForm(OffresType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $offre->setUser($user);
            $entityManager->persist($offre);
            $entityManager->flush();
            $this->addFlash('success', 'Offre ajoutée avec succées!');
            return $this->redirectToRoute('offres_index');
        }

        return $this->render('offres/new.html.twig', [
            'offre' => $offre,
            'form' => $form->createView(),
        ]);
    }




    /**
     * @Route("/seulOff/{id}", name="Single-offres_show", methods={"GET"})
     */
    public function show(Offres $offre ,ArticleRepository $artRepo): Response
    {
        $articlelast1 = $artRepo->findLastArticles2();
        return $this->render('offres/single-offre.html.twig', [
            'offre' => $offre,'articlelast1' => $articlelast1
        ]);
    }

    /**
     * @Route("/show1", name="offres-back", methods={"GET"})

     * @return Response

    public function showFront(Offres $offre): Response
    {
        return $this->render('offres/single-offre-back.html.twig', [
            'offre' => $offre,
        ]);
    } **/
    /**
     * @Route("/{id}", name="offres_show-back", methods={"GET"})
     */
    public function show1(Offres $offre , ArticleRepository $articlerepo): Response
    {
        $articlelast1 = $articlerepo->findLastArticles2();
        return $this->render('offres/show.html.twig', [
            'offre' => $offre,'articlelast1' => $articlelast1
        ]);
    }

    /**
     * @Route("/{id}/edit", name="offres_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Offres $offre): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(OffresType::class, $offre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offre->setUser($user);
            $this->getDoctrine()->getManager()->flush();


            $this->addFlash('info', 'Offre modifié!');
            return $this->redirectToRoute('offres_index');
        }

        return $this->render('offres/edit.html.twig', [
            'offre' => $offre,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="offres_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Offres $offre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$offre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($offre);
            $entityManager->flush();
            $this->addFlash('danger', 'Offre supprimé!');
        }

        return $this->redirectToRoute('offres_index');
    }



    /*    $em = $this->getDoctrine()->getManager();
       $requestString = $request->get('o');
       $offres =  $em->getRepository('Offres:offre')->findEntitiesByString($requestString);
       if(!$offres) {
           $result['offre']['error'] = "article Not found :( ";
       } else {
           $result['offres'] = $this->getRealEntities($offres);
       }
       return new Response(json_encode($result));
   }
   public function getRealEntities($offres): array
   {
       foreach ($offres as $offres){
           $realEntities[$offres->getId()] = [$offres->getPhoto(),$offres->getTitle()];

       }
       return $realEntities;
   }*/


//    /**
//     * @Route("/{id}/valider", name="offre_valider", methods={"GET","POST"})
//     */
//    public function valider(Request $request, Offres $offre): Response
//    {
//        $form = $this->createForm(Offres::class, $offre);
//        $form->handleRequest($request);
//
//        if ($request->isMethod('post')){
//            $val=new Valpub();
//            $val->setValider(false);
//            if ($request->request->get("checkbox")){
//                $val->setValider(true);
//            }
//            $Req=$request->request->get("remarque");
//            $d= new \DateTime("Now");
//
//            $val->setRemarque($Req);
//            $val->setDate($d);
//            $val->setOffres($offre);
//
//            $em= $this->getDoctrine()->getManager();
//            $em->persist($val);
//            $em->flush();
//
//            return $this->redirectToRoute('offre');
//        }
//
//
//    }
//    /**
//     * @Route("/{id}/publier", name="offre_publier", methods={"GET","POST"})
//     */
//    public function publier(Request $request, Offres $offre): Response
//    {
//        $form = $this->createForm(Offres::class, $offre);
//        $form->handleRequest($request);
//
//        if ($request->isMethod('post')){
//            $val=new Valpub();
//            $d= new \DateTime("Now");
//            $val->setPublier(true);
//            $val->setDate($d);
//            $val->setOffres($offre);
//
//            $em= $this->getDoctrine()->getManager();
//            $em->persist($val);
//            $em->flush();
//
//            return $this->redirectToRoute('offre');
//        }
//
//
//    }


}

templates/offres/_delete_form.html.twig
<form method="post" action="{{ path('offres_delete', {'id': offre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/offres/condidature.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}Condidature{% endblock %}

{% block body %}


<section class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_1.jpg');">
    <div class="overlay">

    </div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-2 bread">Postuler une codidature simple</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Acceuil <i class="ion-ios-arrow-forward"></i></a></span>
                    <span class="mr-2"><a href="NousRejoindre.html"> Nous rejoindre<i class="ion-ios-arrow-forward"></i></a></span>
                    <span>offre</span></p>
            </div>
        </div>
    </div>
</section>


<div class="row">

    <div class="col-md-6 offset-md-3 mt-5" style="border: 2px solid #d91a5b;border-radius: 30px " >

        <form accept-charset="UTF-8" action="#" method="POST" enctype="multipart/form-data" target="_blank">
            {{ form_start(form) }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="exampleInputName">Nom </label>
                    {{ form_widget(form.nom, {'attr': {'class': "form-control",'name':"condidature[nom]" ,'id':"condidature_nom" ,'placeholder':"Votre nom",'required':"required"}}) }}

{#                    <input type="text" name="fullname" class="form-control" id="exampleInputName" placeholder="Entrer yvotre nom" required="required">#}
                </div>
                <div class="form-group col-md-6">
                    <label for="exampleInputName">Prenom </label>
                    {{ form_widget(form.prenom, {'attr': {'class': "form-control",'name':"condidature[prenom]" ,'id':"condidature_prenom" ,'placeholder':"Votre prenom",'required':"required"}}) }}

{#                    <input type="text" name="fullname" class="form-control" id="exampleInputName1" placeholder="Entrer votre prenom" required="required">#}
                </div></div>
            <div class="form-group">
                <label for="exampleInputEmail1" required="required">Email </label>
                {{ form_widget(form.email, {'attr': {'class': "form-control",'name':"condidature[email]" ,'id':"condidature_email" ,'placeholder':"Votre email",'required':"required"}}) }}

{#                <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Entrer un address">#}
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1" required="required">Lettre de motivation</label>
                {{ form_widget(form.lm, {'attr': {'class': "form-control",'name':"condidature[lm]" ,'id':"condidature_lm" ,'placeholder':"lettre de motivation",'required':"required"}}) }}

            </div>


            <div class="form-group mt-5">
                <label class="mr-4"> importer votre CV </label>
                {{ form_widget(form.cv, {'attr': {'type': "file",'name':"condidature[lm]" ,'id':"condidature_lm" ,'required':"required"}}) }}

                <input type="file" name="file">
            </div>
            <div class="form-group mt-10 text-center ">

                <button type="submit" class="btn btn-primary btn-lg btn-block">Envoyer</button>

            </div>
            {{ form_end(form) }}
        </form>
    </div>

</div>



<div id="footer" style="padding-top:10px" >
    <div class="footer-newsletter">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h4>Inscrivez-vous</h4>
                    <p>Inscrivez-vous pour recevoir les notifications des nouveautés des domaines l'environnement, l'hygiène et la santé sécurité au travail</p>
                    <form action="" method="post">
                        <input type="email" name="email"><input type="submit" value="S'abonner">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/offres/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Modifier Offres{% endblock %}
{% block head %}
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
 {% endblock %}

{% block body %}
  <div class="card card-custom gutter-b example example-compact">
    <div class="card-header">
    <h3 class="card-title">Modifier Offres</h3>
    </div>
        {{ form_start(form) }}


        <div class="card-body">
            <div class="form-group">
                <label>Type</label>
                {{ form_widget(form.type ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer le type"}})}}
            </div>
            <div class="form-group">
                <label>Titre</label>
                {{ form_widget(form.titre ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer le titre"}})}}
            </div>
            <div class="form-group">
                <label>Nombre</label>
                {{ form_widget(form.nombre ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer un nombre "}})}}</div>
            <div class="form-group">
                <label>Description </label>
                {{ form_widget(form.description ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}})}}
            </div>
            <div class="form-group" >
                <label class="">Date :</label>
                <div class="col-lg-4 col-md-9 col-sm-12">
                    <div class="input-group date" id="kt_datetimepicker_6" data-target-input="nearest">
                        {{ form_widget(form.date,{'attr':{'class':"form-control datetimepicker-input",'data-target':"#kt_datetimepicker_6"}}) }}
                        <div class="input-group-append" data-target="#kt_datetimepicker_6" data-toggle="datetimepicker">
															<span class="input-group-text">
																<i class="ki ki-calendar"></i>
															</span>
                        </div>
                    </div>
                </div>
            </div>
      <div class="form-group">
                <label>Qualification </label>
                {{ form_widget(form.qualification ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer les qualifications"}})}}
            </div>
     <div class="form-group">
                <label>Experience </label>
                {{ form_widget(form.experience ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer l'experience"}})}}
            </div>
     


        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary mr-2">Enregistrer</button>
            <button type="reset" class="btn btn-secondary"><a href="{{ path('offres_index') }}">Retourner au liste</a></button>
        </div>

        {{ form_rest(form) }}
        {{ form_end(form) }}

{% endblock %}

templates/offres/index2.html.twig
{% extends 'basefront.html.twig' %}

    {% block title %}Offres index{% endblock %}

    {% block body %}
        <section class="hero-wrap hero-wrap-2" style="background-image: url('{{ asset('themefront/assets/images/bg_1.jpg')}}');">
            <div class="overlay"></div>
            <div class="container">
                <div class="row no-gutters slider-text align-items-center justify-content-center">
                    <div class="col-md-9 ftco-animate text-center">
                        <h1 class="mb-2 bread"> Nos Offres</h1>
                        <p class="breadcrumbs"><span class="mr-2"><a href="{{ path('accueil') }}">Acceuil <i
                                            class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a
                                        href="{{ path('offresF_index') }}">  Nous Rejoindre</a>
                </span>
                        </p>
                    </div>
                </div>
            </div>
        </section>



        <section class="ftco-section bg-light">
            <div class="container">
                <div class="row">

                    <div class="col-lg-9 pr-lg-4">
                        {% for offre in offres  %}
                            <div class="row">

                                <div class="col-md-12 ftco-animate">
                                    <div class="job-post-item p-4 d-block d-lg-flex align-items-center">
                                        <div class="one-third mb-4 mb-md-0">
                                            <div class="job-post-item-header align-items-center">

                                                <h2 class="mr-3 text-black"><a href="#">{{ offre.titre}}</a></h2>
                                            </div>
                                            <div class="job-post-item-body d-block d-md-flex">
                                                <div class="mr-3"><span class="icon-layers"></span> <a href="{{ path('Single-offres_show', {'id': offre.id}) }}" >{{ offre.type }}</a></div>
                                                <div><span class="icon-check"></span> <span>{{ offre.experience }}</span></div>
                                            </div>
                                        </div>

                                        <div class="one-forth ml-auto d-flex align-items-center mt-4 md-md-0">

                                            <a href="{{ path('Single-offres_show', {'id': offre.id}) }}" class="btn btn-primary  py-3 px-3">Postuler</a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        {% else %}
                            <h4>Aucun offre</h4>
                        {% endfor %}

                        <div class="navigation text-center  st-color-blue d-flex justify-content-center " >
                            {{ knp_pagination_render(offres) }}
                        </div>


                    </div>
                    <div class="col-lg-3 sidebar">


                        <div class="row">
                            <div class="col-sm-4">
                                <div class="main-button">

                                    {% if is_granted('ROLE_USER')  %}
                                        <a href="{{ path('condidature') }}"style="color:#d91a5b;border-color: #d91a5b;background-color: white" class="btn">Candidature spontannée</a>
                                    {% else %}
                                        <a href="{{ path('fos_user_security_login') }}"style="color:#d91a5b;border-color: #d91a5b;background-color: white" class="btn">Candidature spontannée</a>
                                    {% endif %}

                                </div>
                            </div>
                        </div>









                        <div class="sidebar-box bg-white p-4 ftco-animate">
                            <h3 class="heading-sidebar">Rechercher une offre</h3>
                            <form action="" method="get" id="formsearch" class="search-form mb-3">
                                <div class="form-group">
                                    <span class="icon icon-search"></span>
                                    <input type="text" name="o" class="form-control" placeholder="Search..." id="search">
                                </div>


                                <h3 class="heading-sidebar">Type offre</h3>

                                <label for="option-job-type-1"><input type="radio" id="option-job-type-1" name="tes" value="1" > Emploi</label><br>
                                <label for="option-job-type-2"><input type="radio" id="option-job-type-2" name="tes" value="2"> Stage</label><br>
                                <button class="btn btn-primary" type="submit" style="color:#d91a5b;border-color: #d91a5b;background-color: white ">Recherche</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>


    {% endblock %}