src/Entity/Partenaire.php
<?php

namespace App\Entity;

use App\Repository\PartenaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=PartenaireRepository::class)
 */
class Partenaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $localisation;

    /**
     * @ORM\Column(type="integer")
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $responsable;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $secteur_activite;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user",referencedColumnName="id")
     */
    private $User;



    public function __construct()
    {



    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getResponsable(): ?string
    {
        return $this->responsable;
    }

    public function setResponsable(string $responsable): self
    {
        $this->responsable = $responsable;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSecteurActivite(): ?string
    {
        return $this->secteur_activite;
    }

    public function setSecteurActivite(string $secteur_activite): self
    {
        $this->secteur_activite = $secteur_activite;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImage(): ?string
    {
    return $this->Image;
    }
    public function setImage(string $Image): self
    {
    $this->Image = $Image;

    return $this;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->User;
    }

    /**
     * @param User $User
     * @return Partenaire
     */
    public function setUser(User $User): Partenaire
    {
        $this->User = $User;
        return $this;
    }




}

src/Form/PartenaireType.php
<?php

namespace App\Form;

use App\Entity\Partenaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartenaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class,[
                "attr" =>[
                    "class"=>"form-control"
                ]
            ])
            ->add('adress', TextType::class,[
                "attr" =>[
                    "class"=>"form-control"
                ]
            ])
            ->add('localisation', TextType::class,[
                "attr" =>[
                    "class"=>"form-control"
                ]
            ])
            ->add('telephone')
            ->add('email')
            ->add('responsable', TextType::class,[
                "attr" =>[
                    "class"=>"form-control"
                ]
            ])
            ->add('type', TextType::class,[
                "attr" =>[
                    "class"=>"form-control"
                ]
            ])
            ->add('description', TextType::class,[
                "attr" =>[
                    "class"=>"form-control"
                ]
            ])
            ->add('secteur_activite', TextType::class,[
                "attr" =>[
                    "class"=>"form-control"
                ]
            ])
            ->add('image', FileType::class, [
                'mapped'=>false,
                'required'=>false
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Partenaire::class,
        ]);
    }
}

src/Controller/PartenaireController.php
<?php

namespace App\Controller;


use App\Entity\Media;
use App\Entity\Partenaire;
use App\Form\PartenaireType;
use App\Repository\ArticleRepository;
use App\Repository\PartenaireRepository;
use Doctrine\ORM\Mapping\Id;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\DomCrawler\Image;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;


/**
 * @Route("/partenaire")
 */
class PartenaireController extends AbstractController
{
    /**
     * @Route("/", name="partenaire_index", methods={"GET"})
     */
    public function index(PartenaireRepository $partenaireRepository, Request $request,PaginatorInterface $paginator)
    {
        $em=$this->getDoctrine()->getManager();
        $search = $request->query->get('p');
        if ($search) {
            $partenaires = $partenaireRepository->search($search);
        } else {
            $partenaires = $partenaireRepository->findAll();
        }
        $partenaire = $paginator->paginate(
            $partenaires,
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('partenaire/index.html.twig', [
            'partenaires' => $partenaire,
        ]);
    }


    /**
     * @Route("/new", name="partenaire_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        $partenaire = new Partenaire();
        $form = $this->createForm(PartenaireType::class, $partenaire);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            /**
             * @var image $image
             */
            $image= $form->get('image')->getData();
            $em = $this->getDoctrine()->getManager();

            $em->persist($partenaire);

            if ($image) {
                $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $image->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $image->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {

                }

                $partenaire->setImage($newFilename);
                /* $media = new Media();
                 $media->setURL($newFilename);
                 $media->setPartenaire($partenaire);
                 $em->persist($media);
                 $em->flush();*/
            }

                $partenaire->setUser($user);
                $em->persist($partenaire);
                $em->flush();
                $this->addFlash('success', 'partenaire Creé! ');
                return $this->redirectToRoute('partenaire_index');


        }

        return $this->render('partenaire/new.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/List/", name="partenaire_list", methods={"GET"})
     */
    public function showList(ArticleRepository $articlerepo): Response
    {
        $articlelast1 = $articlerepo->findLastArticles2();
        $em=$this->getDoctrine()->getManager();
        $partenaires = $em->getRepository(Partenaire::class)->findAll();

        return $this->render('partenaire/show1.html.twig', [
            'partenaires' => $partenaires,'articlelast1' => $articlelast1
        ]);
    }


    /**
     * @Route("/{id}", name="partenaire_show", methods={"GET"})
     */
    public function show(Partenaire $partenaire): Response
    {
        return $this->render('partenaire/show.html.twig', [
            'partenaire' => $partenaire,
        ]);
    }



    /**
     * @Route("/{id}/edit", name="partenaire_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Partenaire $partenaire): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(PartenaireType::class, $partenaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $partenaire->setUser($user);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('info', 'partenaire modifié!');
            return $this->redirectToRoute('partenaire_index');
        }

        return $this->render('partenaire/edit.html.twig', [
            'partenaire' => $partenaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="partenaire_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Partenaire $partenaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$partenaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($partenaire);
            $entityManager->flush();
        }
        $this->addFlash('danger', 'partenaire supprimé!');
        return $this->redirectToRoute('partenaire_index');
    }
}

templates/partenaire/_delete_form.html.twig
<form method="post" action="{{ path('partenaire_delete', {'id': partenaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ partenaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/partenaire/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Modifier Partenaire{% endblock %}
{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
{% endblock %}
{% block body %}
    <div class="card card-custom gutter-b example example-compact">
        <div class="card-header">
            <h3 class="card-title">Modifier Partenaire</h3>
        </div>

        {{ form_start(form) }}

        <div class="card-body">
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg">Nom</label>
                {{ form_widget(form.nom ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg">Adresse</label>
                {{ form_widget(form.adress ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg">Localisation</label>
                {{ form_widget(form.localisation,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg" >Téléphone</label>
                {{ form_widget(form.telephone ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg" >Email</label>
                {{ form_widget(form.email ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg" >Responsable</label>
                {{ form_widget(form.responsable ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg" >Type</label>
                {{ form_widget(form.type ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg">Secteur d'activité</label>
                {{ form_widget(form.secteur_activite ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>
            <div class="form-group">
                <label class="text-dark font-weight-bolder  d-block my-1 font-size-lg" >Description</label>
                {{ form_widget(form.description ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
            </div>

            <div class="form-group">
                <td class="pl-0">
                    <div class="text-dark font-weight-bolder  d-block my-1 font-size-lg">Image</div>

                </td>
                {{ form_widget(form.image) }}

            </div>
        </div>

    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary mr-2">Enregistrer</button>
        <button type="reset" class="btn btn-secondary"><a href="{{ path('partenaire_index') }}">Retourner au liste</a>
        </button>
    </div>

    {{ form_rest(form) }}
    {{ form_end(form) }}

{% endblock %}

templates/partenaire/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Partenaire {% endblock %}

{% block body %}
    <div class="card card-custom gutter-b" >
        <!--begin::Header--> <div class="container  align-items-stretch ">


        </div>
        <div class="card-header border-0 py-5" >
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label font-weight-bolder text-dark">liste des partenaires</span>

            </h3>
            <div class="card-toolbar">
                <a href="{{ path('partenaire_new') }}" class="btn btn-success font-weight-bolder font-size-sm">
											<span class="svg-icon svg-icon-md svg-icon-white">

											</span>Ajouter un nouveau partenaire</a>
            </div>
        </div>


        <!--begin::Body-->

        <div class="card-body py-0" >
            <form class="form" action="" method="get" id="formsearch1">

                <div class="form-group row">
                    <input type="text" name="p" class="form-control col-8" placeholder="recherche..."/>
                    <button type="submit" class="btn btn-primary mr-2 "><span><i class="flaticon2-search-1 icon-md"></i></span></button>
                </div>


            </form>
            <!--begin::Table-->
            <div class="table-responsive" >
                <table class="table table-head-custom table-vertical-center" id="kt_advance_table_widget_1" style="height:100%" >
                    <thead>
                    <tr class="table-primary">
                        <th>Id</th>
                        <th>Nom</th>
                        <th>Localisation</th>
                        <th>Responsable</th>
                        <th>Type</th>
                        <th>Secteur_activite</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for partenaire in partenaires %}
                        <tr height="100%">
                            <td>{{ partenaire.id }}</td>
                            <td>{{ partenaire.nom }}</td>
                            <td>{{ partenaire.localisation }}</td>
                            <td>{{ partenaire.responsable }}</td>
                            <td>{{ partenaire.type }}</td>
                            <td>{{ partenaire.secteurActivite }}</td>

                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           <span class="svg-icon svg-icon-primary svg-icon-2x"><!--begin::Svg Icon | path:/var/www/preview.keenthemes.com/metronic/releases/2021-03-30-161050/theme/html/demo1/dist/../src/media/svg/icons/General/Settings-2.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <rect x="0" y="0" width="24" height="24"/>
        <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z" fill="#000000"/>
    </g>
</svg><!--end::Svg Icon--></span>
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{{ path('partenaire_edit', {'id': partenaire.id}) }}"><span class="svg-icon svg-icon-primary svg-icon-2x"><!--begin::Svg Icon | path:C:\wamp64\www\keenthemes\themes\metronic\theme\html\demo1\dist/../src/media/svg/icons\Communication\Write.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <rect x="0" y="0" width="24" height="24"/>
        <path d="M12.2674799,18.2323597 L12.0084872,5.45852451 C12.0004303,5.06114792 12.1504154,4.6768183 12.4255037,4.38993949 L15.0030167,1.70195304 L17.5910752,4.40093695 C17.8599071,4.6812911 18.0095067,5.05499603 18.0083938,5.44341307 L17.9718262,18.2062508 C17.9694575,19.0329966 17.2985816,19.701953 16.4718324,19.701953 L13.7671717,19.701953 C12.9505952,19.701953 12.2840328,19.0487684 12.2674799,18.2323597 Z" fill="#000000" fill-rule="nonzero" transform="translate(14.701953, 10.701953) rotate(-135.000000) translate(-14.701953, -10.701953) "/>
        <path d="M12.9,2 C13.4522847,2 13.9,2.44771525 13.9,3 C13.9,3.55228475 13.4522847,4 12.9,4 L6,4 C4.8954305,4 4,4.8954305 4,6 L4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 L2,6 C2,3.790861 3.790861,2 6,2 L12.9,2 Z" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
    </g>
</svg><!--end::Svg Icon--></span>&ensp;Modifier</a>

                                        <a class="dropdown-item" href="{{ path('partenaire_show', {'id': partenaire.id}) }}"><span class="svg-icon svg-icon-primary svg-icon-2x"><!--begin::Svg Icon | path:C:\wamp64\www\keenthemes\themes\metronic\theme\html\demo1\dist/../src/media/svg/icons\Communication\Thumbtack.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <rect x="0" y="0" width="24" height="24"/>
        <path d="M11.6734943,8.3307728 L14.9993074,6.09979492 L14.1213255,5.22181303 C13.7308012,4.83128874 13.7308012,4.19812376 14.1213255,3.80759947 L15.535539,2.39338591 C15.9260633,2.00286161 16.5592283,2.00286161 16.9497526,2.39338591 L22.6066068,8.05024016 C22.9971311,8.44076445 22.9971311,9.07392943 22.6066068,9.46445372 L21.1923933,10.8786673 C20.801869,11.2691916 20.168704,11.2691916 19.7781797,10.8786673 L18.9002333,10.0007208 L16.6692373,13.3265608 C16.9264145,14.2523264 16.9984943,15.2320236 16.8664372,16.2092466 L16.4344698,19.4058049 C16.360509,19.9531149 15.8568695,20.3368403 15.3095595,20.2628795 C15.0925691,20.2335564 14.8912006,20.1338238 14.7363706,19.9789938 L5.02099894,10.2636221 C4.63047465,9.87309784 4.63047465,9.23993286 5.02099894,8.84940857 C5.17582897,8.69457854 5.37719743,8.59484594 5.59418783,8.56552292 L8.79074617,8.13355557 C9.76799113,8.00149544 10.7477104,8.0735815 11.6734943,8.3307728 Z" fill="#000000"/>
        <polygon fill="#000000" opacity="0.3" transform="translate(7.050253, 17.949747) rotate(-315.000000) translate(-7.050253, -17.949747) " points="5.55025253 13.9497475 5.55025253 19.6640332 7.05025253 21.9497475 8.55025253 19.6640332 8.55025253 13.9497475"/>
    </g>
</svg><!--end::Svg Icon--></span>&ensp;Afficher</a>

                                        <!-- <a class="dropdown-item" href="#">Something else here</a>-->
                                        {% if app.user  %}
                                        {% if is_granted('ROLE_ADMIN')  %}
                                        <a class="dropdown-item" onclick="$('#delF').submit() "><span class="svg-icon svg-icon-primary svg-icon-2x"><!--begin::Svg Icon | path:C:\wamp64\www\keenthemes\themes\metronic\theme\html\demo1\dist/../src/media/svg/icons\General\Trash.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <rect x="0" y="0" width="24" height="24"/>
        <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z" fill="#000000" fill-rule="nonzero"/>
        <path d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z" fill="#000000" opacity="0.3"/>
    </g>
</svg><!--end::Svg Icon--></span>&ensp;Supprimer</a>
                                        {% else %}{% endif %}{% endif %}
                                        <form id="delF" method="post" action="{{ path('partenaire_delete', {'id': partenaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ partenaire.id) }}">
                                        </form>

                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4">aucun enregistrement trouvé</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
            <!--end::Table-->
            <div class="navigation text-center  st-color-blue d-flex justify-content-center "  style="font-size: large ; letter-spacing: 5px ; color:#eb1c1c">
                {{ knp_pagination_render(partenaires) }}
            </div>
        </div>
        <!--end::Body-->
    </div>


{% endblock %}

templates/partenaire/new.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Nouveau Partenaire{% endblock %}
{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
{% endblock %}
{% block body %}
<div class="card card-custom gutter-b example example-compact">
    <div class="card-header">
        <h3 class="card-title">Ajouter un partenaire</h3>
    </div>
    {{ form_start(form) }}
    <div class="card-body">
        <div class="form-group">
            <label>Nom</label>
            {{ form_widget(form.nom ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            <label>Adresse</label>
            {{ form_widget(form.adress ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            <label>Localisation</label>
            {{ form_widget(form.localisation,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            <label>Téléphone</label>
            {{ form_widget(form.telephone ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            <label>Email</label>
            {{ form_widget(form.email ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            <label>Responsable</label>
            {{ form_widget(form.responsable ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            <label>Type</label>
            {{ form_widget(form.type ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            <label>Secteur d'activité</label>
            {{ form_widget(form.secteur_activite ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            <label>Description</label>
            {{ form_widget(form.description ,{'attr':{'class':"form-control form-control-solid",'placeholder':"Entrer une description"}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.image) }}
            {{ form_widget(form.image) }}


        </div>
    </div>

    <div class="card-footer">
        <button type="submit" class="btn btn-primary mr-2">Enregistrer</button>
        <button type="reset" class="btn btn-secondary"><a href="{{ path('partenaire_index') }}">Retourner au liste</a></button>
    </div>
    {{ form_rest(form) }}
    {{ form_end(form) }}
</div>
{% endblock %}