src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CalendarRepository::class)
 */
class Calendar
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $all_day;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $background_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $border_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $text_color;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $delais;

    /**
     * @ORM\Column(type="date")
     */
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $theme;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $localisation;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user",referencedColumnName="id")
     */
    private $User;





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;

    }



    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->title;
    }

    public function setTitre(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }





    public function getDelais(): ?string
    {
        return $this->delais;
    }

    public function setDelais(string $delais): self
    {
        $this->delais = $delais;

        return $this;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->User;
    }

    /**
     * @param User $User
     * @return Calendar
     */
    public function setUser(User $User): Calendar
    {
        $this->User = $User;
        return $this;
    }





}

src/Entity/Recherche.php
<?php

namespace App\Entity;

use App\Repository\RechercheRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RechercheRepository::class)
 */
class Recherche
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_recherche;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $requete;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $resultat;
    /**
      * @var User
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user",referencedColumnName="id")
     * 
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateRecherche(): ?\DateTimeInterface
    {
        return $this->date_recherche;
    }

    public function setDateRecherche(\DateTimeInterface $date_recherche): self
    {
        $this->date_recherche = $date_recherche;

        return $this;
    }

    public function getRequete(): ?string
    {
        return $this->requete;
    }

    public function setRequete(string $requete): self
    {
        $this->requete = $requete;

        return $this;
    }

    public function getResultat(): ?string
    {
        return $this->resultat;
    }

    public function setResultat(string $resultat): self
    {
        $this->resultat = $resultat;

        return $this;
    }
}

src/Controller/RechercheController.php
<?php

namespace App\Controller;

use App\Entity\Recherche;
use App\Form\RechercheType;
use App\Repository\ArticleRepository;
use App\Repository\RechercheRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/recherche")
 */
class RechercheController extends AbstractController
{
    /**
     * @Route("/", name="recherche_index", methods={"GET"})
     */
    public function index(RechercheRepository $rechercheRepository): Response
    {
        return $this->render('recherche/index.html.twig', [
            'recherches' => $rechercheRepository->findAll(),
        ]);
    }


    /**
     * @Route("/recherche", name="recherche_show", methods={"Post"})
     */
    public function show(Request $request,PaginatorInterface $paginator ,ArticleRepository $artRepo): Response
    {
        $articlelast1 = $artRepo->findLastArticles2();
        $search = $request->request->get('search');
        $tab=explode(' ',$search );
        $tab2=array();
        $k=0;
        foreach ($tab as $e ){
            if ($e){
                $tab2[$k]= $e;
                $k++;
            }

        }
        $ch= implode('|',$tab2);
        $em=$this->getDoctrine()->getConnection();
       $query= $em->executeQuery("select p.id as id, p.titre as titre, p.contenu as contenu, p.slug as url ,1 as elpage from  page p  where   p.titre REGEXP  '".$ch."' or p.contenu  REGEXP  '".$ch."' 
union 
select a.id as id, a.titre as titre, a.contenu as contenu, null as url ,0 as elpage from article a  where   a.titre REGEXP  '".$ch."' or a.contenu  REGEXP  '".$ch."'");
        $recherche=$query->fetchAllAssociative();
       /* $recherche =  $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            10
        );

        $em->persist($search);
        $em->flush();*/
        return $this->render('recherche/show.html.twig', [
            'search' => $search,
            'elements' => $recherche,'articlelast1' => $articlelast1
        ]);
    }


    /**
     * @Route("/{id}", name="recherche_delete", methods={"POST"})
     */
    public function delete(Request $request, Recherche $recherche): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recherche->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($recherche);
            $entityManager->flush();
        }

        return $this->redirectToRoute('recherche_index');
    }
}

templates/recherche/_delete_form.html.twig
<form method="post" action="{{ path('recherche_delete', {'id': recherche.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recherche.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recherche/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Recherche index{% endblock %}

{% block body %}
    <h1>Recherche index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_recherche</th>
                <th>Requete</th>
                <th>Resultat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for recherche in recherches %}
            <tr>
                <td>{{ recherche.id }}</td>
                <td>{{ recherche.dateRecherche ? recherche.dateRecherche|date('Y-m-d') : '' }}</td>
                <td>{{ recherche.requete }}</td>
                <td>{{ recherche.resultat }}</td>
                <td>
                    <a href="{{ path('recherche_show', {'id': recherche.id}) }}">show</a>
                    <a href="{{ path('recherche_edit', {'id': recherche.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('recherche_new') }}">Create new</a>
{% endblock %}

templates/recherche/show.html.twig
{% extends 'basefront.html.twig' %}

{% block title %}Recherche : {% endblock %}

{% block body %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url('{{ asset('themefront/assets/images/bg_1.jpg')}}');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <h1 class="mb-2 bread">Recherche : {{ search }}</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 pr-lg-4">  {% for element in elements %}
                    <div class="row">
                        <div class="col-md-12 ftco-animate">
                            <div class="job-post-item p-4 d-block d-lg-flex align-items-center">

                                <div class="one-third mb-4 mb-md-0">
                                    <div class="job-post-item-header align-items-center">
                                        <span class="subadge"> {{ element.id }}</span>
                                        <h2 class="mr-3 text-black"><a
                                                    {% if (element.elpage==1) %}
                                                    href="{{path('page_show2' , {'slug' : element.url}) }}"
{% else %}
                                                    href="{{ path('show', {'id': element.id}) }}"
                                                    {% endif %}
                                            > {{ element.titre }}</a></h2>
                                    </div>
                                    <div class="job-post-item-body d-block d-md-flex">
                                        <div class="mr-3"><span class="icon-layers"></span> <a href="#">{{ element.url }}.</a></div>
                                        <div><span class="icon-my_location"></span> <span>{{ element.elpage }}</span></div>
                                    </div>
                                </div>

                            </div>
                        </div><!-- end -->
                    </div> {% endfor %}
                </div>
            </div>
        </div>
    </section>


{% endblock %}